[package]
name = "rs_offchain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.64"
tokio = "1.20.1"

sui-sdk = { git = "https://github.com/MystenLabs/sui", branch = "devnet" }
